# Generated by Django 6.1.1 on 2026-09-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('opis_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada')], max_length=2)),
                ('rack_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=8, help_text='USD per gallon, lowest seen for this ID.', max_digits=12)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius_miles', models.FloatField(help_text='Approximate radius of the city the station is placed in.')),
                ('location_precision', models.CharField(default='city', max_length=10)),
                ('geocode_source', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['opis_id'],
            },
        ),
    ]
